import { ShieldCheck, Target, HeartHandshake, Zap, Info, Calendar as CalendarIcon, Clock, MapPin } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { useParams, useNavigate } from 'react-router-dom';
import axios from 'axios';
import { GaugeChart } from '../components/charts/GaugeChart';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Modal } from '../components/ui/Modal';
import { Input } from '../components/ui/Input';
import { useState } from 'react';

export default function TrustScoreDetail() {
  const { providerId } = useParams();
  const navigate = useNavigate();
  const [isBookingModalOpen, setIsBookingModalOpen] = useState(false);
  const [bookingStep, setBookingStep] = useState(1);
  const [isBookingLoading, setIsBookingLoading] = useState(false);

  const handleBookingConfirm = async () => {
    setIsBookingLoading(true);
    try {
      await axios.post('http://localhost:5000/api/bookings', { providerId });
      setBookingStep(2);
    } catch (error) {
      console.error('Booking failed', error);
      alert('Failed to book provider.');
    } finally {
      setIsBookingLoading(false);
    }
  };
  
  const factors = [
    { name: 'Ratings & Reviews', impact: '+25', icon: Target, color: 'text-blue-500', bg: 'bg-blue-100 dark:bg-blue-900/30' },
    { name: 'Repeat Customers', impact: '+12', icon: HeartHandshake, color: 'text-green-500', bg: 'bg-green-100 dark:bg-green-900/30' },
    { name: 'Fast Response', impact: '+8', icon: Zap, color: 'text-yellow-500', bg: 'bg-yellow-100 dark:bg-yellow-900/30' },
    { name: 'Identity Verified', impact: '+15', icon: ShieldCheck, color: 'text-purple-500', bg: 'bg-purple-100 dark:bg-purple-900/30' }
  ];

  return (
    <div className="max-w-5xl mx-auto px-4 py-8">
      <div className="flex flex-col md:flex-row gap-8 items-start">
        <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} className="w-full md:w-1/3">
          <Card className="p-8 text-center bg-gradient-to-b from-gray-50 to-white dark:from-gray-900 dark:to-gray-950">
            <h2 className="text-xl font-bold mb-8 text-gray-900 dark:text-white">Provider Trust Score</h2>
            <GaugeChart score={84} />
            <div className="mt-8 pt-6 border-t border-gray-200 dark:border-gray-800">
              <div className="flex items-center justify-center gap-2 text-green-600 dark:text-green-400 font-medium mb-4">
                <ShieldCheck className="w-5 h-5" />
                <span>Highly Trusted</span>
              </div>
              <Button size="lg" className="w-full h-14 text-lg font-bold shadow-xl shadow-primary-500/20" onClick={() => setIsBookingModalOpen(true)}>
                Book This Provider
              </Button>
            </div>
          </Card>
        </motion.div>

        <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="w-full md:w-2/3 space-y-6">
          <div className="bg-primary-50 dark:bg-primary-900/20 p-6 rounded-2xl border border-primary-100 dark:border-primary-900/50 flex gap-4">
            <Info className="w-6 h-6 text-primary-600 shrink-0 mt-1" />
            <div>
              <h3 className="font-semibold text-primary-900 dark:text-primary-100 mb-2">How AI calculates this score</h3>
              <p className="text-sm text-primary-800 dark:text-primary-200/80 leading-relaxed">
                The TrustScore is dynamically generated by our TrustEngine AI. It analyzes hundreds of data points including review authenticity, job completion rate, late cancellations, and customer retention. It drops drastically if suspicious behavior is flagged.
              </p>
            </div>
          </div>

          <div className="grid sm:grid-cols-2 gap-4">
            {factors.map((factor, idx) => (
              <motion.div 
                key={factor.name}
                initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: idx * 0.1 }}
                className="bg-white dark:bg-gray-900 p-5 rounded-xl border border-gray-100 dark:border-gray-800 shadow-sm flex items-center justify-between"
              >
                <div className="flex items-center gap-4">
                  <div className={`p-3 rounded-lg ${factor.bg}`}>
                    <factor.icon className={`w-5 h-5 ${factor.color}`} />
                  </div>
                  <span className="font-medium text-gray-900 dark:text-gray-100">{factor.name}</span>
                </div>
                <span className="font-bold text-green-500">{factor.impact}</span>
              </motion.div>
            ))}
          </div>

          <Card className="p-6">
             <h3 className="font-bold mb-4">Historical Performance</h3>
             <div className="space-y-3">
               <div className="flex justify-between text-sm">
                 <span className="text-gray-500">Job Completion Rate</span>
                 <span className="font-medium">98%</span>
               </div>
               <div className="w-full bg-gray-100 dark:bg-gray-800 rounded-full h-2">
                 <div className="bg-green-500 h-2 rounded-full" style={{ width: '98%' }}></div>
               </div>
               
               <div className="flex justify-between text-sm pt-3">
                 <span className="text-gray-500">Cancellation Rate</span>
                 <span className="font-medium text-red-500">2%</span>
               </div>
               <div className="w-full bg-gray-100 dark:bg-gray-800 rounded-full h-2">
                 <div className="bg-red-500 h-2 rounded-full" style={{ width: '2%' }}></div>
               </div>
             </div>
           </Card>
        </motion.div>
      </div>

      <Modal isOpen={isBookingModalOpen} onClose={() => { setIsBookingModalOpen(false); setBookingStep(1); }} title="Book Service">
        <div className="pt-2">
          {bookingStep === 1 ? (
            <div className="space-y-6">
              <div className="bg-blue-50 dark:bg-blue-900/20 p-4 rounded-xl flex items-center justify-between border border-blue-100 dark:border-blue-900/50">
                 <div>
                   <h4 className="font-semibold text-blue-900 dark:text-blue-100">Estimated Base Price</h4>
                   <p className="text-xs text-blue-600 dark:text-blue-300 mt-1">Pricing is finalized after inspection.</p>
                 </div>
                 <div className="text-3xl font-black text-primary-600 dark:text-primary-400">₹250</div>
              </div>
              <div className="space-y-4">
                 <div>
                    <label className="text-sm font-medium mb-1 flex items-center gap-2"><MapPin className="w-4 h-4 text-gray-400" /> Service Address</label>
                    <Input placeholder="Enter flat, building, street..." />
                 </div>
                 <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="text-sm font-medium mb-1 flex items-center gap-2"><CalendarIcon className="w-4 h-4 text-gray-400" /> Date</label>
                      <Input type="date" />
                    </div>
                    <div>
                      <label className="text-sm font-medium mb-1 flex items-center gap-2"><Clock className="w-4 h-4 text-gray-400" /> Time</label>
                      <select className="w-full h-9 rounded-md border border-gray-200 bg-transparent px-3 py-1 text-sm dark:border-gray-800 dark:bg-gray-950 focus:ring-1 focus:ring-primary-600 outline-none">
                        <option>Morning (9AM - 12PM)</option>
                        <option>Afternoon (12PM - 4PM)</option>
                        <option>Evening (4PM - 8PM)</option>
                      </select>
                    </div>
                 </div>
                 <div>
                    <label className="text-sm font-medium mb-1 flex items-center gap-2"><Info className="w-4 h-4 text-gray-400" /> Issue Description</label>
                    <textarea rows={3} className="w-full rounded-md border border-gray-200 bg-transparent px-3 py-2 text-sm dark:border-gray-800 dark:bg-gray-950" placeholder="Briefly describe what needs to be fixed..."></textarea>
                 </div>
              </div>
              <Button className="w-full h-12 text-lg" disabled={isBookingLoading} onClick={handleBookingConfirm}>
                {isBookingLoading ? 'Confirming...' : 'Confirm Booking'}
              </Button>
            </div>
          ) : (
            <motion.div initial={{ scale: 0.9, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} className="flex flex-col items-center justify-center py-10 space-y-4 text-center">
              <div className="w-20 h-20 bg-green-100 dark:bg-green-900/30 text-green-500 rounded-full flex items-center justify-center">
                 <ShieldCheck className="w-10 h-10" />
              </div>
              <h2 className="text-2xl font-bold">Booking Confirmed!</h2>
              <p className="text-gray-500">Your provider has been notified. You can track their status and directly chat with them in your active bookings.</p>
              <Button className="mt-8 w-full h-12 gap-2" onClick={() => navigate('/bookings/history')}>Go to My Bookings</Button>
            </motion.div>
          )}
        </div>
      </Modal>
    </div>
  );
}
